/**
 * MoreOptionsSection — collapsible "More Options" details (due date, payment
 * method, tax, currency + FX preview, notes). Advanced mode only.
 * Extracted verbatim from TransactionFormModal (Ledger phase-6 decomposition).
 * Receives the parent's react-hook-form handle via `form` (same pattern as
 * SimpleEntrySection) so all state stays in the ONE form instance.
 */
import { ChevronUp, ChevronDown, Sparkles } from 'lucide-react'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'

export default function MoreOptionsSection({
  form: { register, watch, setValue },
  currency, currencyOptions, convPreview,
  requiresCustomer, requiresVendor,
  invoiceAutoGenerated, setInvoiceAutoGenerated,
  showOptional, onToggle,
}) {
  const watchedInvoiceNumber = watch('invoiceNumber')
  const watchedAmount = watch('amount')
  return (
    <div className="border border-glass rounded-xl overflow-hidden">
      <button type="button" onClick={onToggle}
        className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-text-secondary hover:text-text-primary hover:bg-glass-hover transition-colors">
        <span className="flex items-center gap-2">
          <span>More Options</span>
          <span className="text-text-muted text-xs font-normal">— due date · payment method · tax · currency · notes</span>
        </span>
        {showOptional ? <ChevronUp className="h-4 w-4 flex-shrink-0" /> : <ChevronDown className="h-4 w-4 flex-shrink-0" />}
      </button>
      {showOptional && (
        <div className="px-4 pb-4 pt-1 space-y-4 border-t border-glass animate-fade-in">
          {/* Invoice number inside More Options (only for non-AR/AP types) */}
          {!requiresCustomer && !requiresVendor && (
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-xs font-medium text-text-secondary">Invoice / Bill Reference</label>
                {invoiceAutoGenerated && watchedInvoiceNumber?.trim() && (
                  <span className="text-xs text-accent/70 flex items-center gap-1">
                    <Sparkles className="h-2.5 w-2.5" />
                    Auto-generated — type to override
                  </span>
                )}
              </div>
              <input
                type="text"
                className="w-full px-3 py-2 rounded-lg bg-glass-panel border border-glass text-text-primary text-sm placeholder:text-text-muted focus:border-accent focus:outline-none transition-colors"
                placeholder="e.g., INV-202601-00042 or BILL-202601-00042"
                {...register('invoiceNumber')}
                onChange={(e) => {
                  register('invoiceNumber').onChange(e)
                  setInvoiceAutoGenerated(false)
                }}
              />
            </div>
          )}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Input label="Reference Number" placeholder="e.g., REF-2024-001" {...register('referenceNumber')} />
            <Input label="Payment Due Date" type="date" {...register('dueDate')} />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Select label="Payment Method" options={[
              { value: '',              label: '— Select —' },
              { value: 'cash',          label: 'Cash' },
              { value: 'bank',          label: 'Bank Transfer' },
              { value: 'credit_card',   label: 'Credit Card' },
              { value: 'debit_card',    label: 'Debit Card' },
              { value: 'cheque',        label: 'Cheque' },
              { value: 'mobile_wallet', label: 'Mobile Wallet (JazzCash/EasyPaisa)' },
              { value: 'online',        label: 'Online (PayPal/Stripe)' },
            ]} value={watch('paymentMethod') || ''} onChange={(v) => setValue('paymentMethod', v)} />
            <Select
              label="Currency"
              options={currencyOptions}
              value={watch('txnCurrency') || currency}
              onChange={(v) => setValue('txnCurrency', v)}
            />
          </div>
          {watch('txnCurrency') && watch('txnCurrency') !== currency && (
            <div className="space-y-2">
              <Input
                label={`Exchange Rate (1 ${watch('txnCurrency')} = ? ${currency})`}
                type="number" step="0.0001" min="0" placeholder="e.g., 280.50"
                {...register('exchangeRate', { valueAsNumber: true })}
              />
              {/* Live conversion preview */}
              {convPreview && (
                <div className="flex items-center gap-2 rounded-lg border border-accent/20 bg-accent/5 px-3 py-2 text-xs">
                  <span className="text-text-muted">Preview:</span>
                  <span className="font-mono font-semibold text-text-primary">
                    {watchedAmount?.toLocaleString()} {watch('txnCurrency')}
                  </span>
                  <span className="text-text-muted">→</span>
                  <span className="font-mono font-bold text-accent">
                    {convPreview.converted?.toLocaleString(undefined, { maximumFractionDigits: 2 })} {currency}
                  </span>
                  <span className="ml-auto text-text-muted">@ {convPreview.rate}</span>
                </div>
              )}
            </div>
          )}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Input label={`Tax Amount (${currency}) — optional`} type="number" step="0.01" min="0"
              placeholder="GST / WHT amount" {...register('taxAmount', { valueAsNumber: true })} />
            <Input label="Tax Rate (%) — optional" type="number" step="0.1" min="0" max="100"
              placeholder="e.g., 17 for 17% GST" {...register('taxRate', { valueAsNumber: true })} />
          </div>
          <div>
            <label className="block text-xs font-medium text-text-secondary mb-1">Notes (internal)</label>
            <textarea rows={2} placeholder="Optional internal notes about this transaction…"
              className="w-full px-3 py-2 rounded-lg bg-glass-panel border border-glass text-text-primary text-sm placeholder:text-text-muted focus:border-accent focus:outline-none resize-none transition-colors"
              {...register('notes')} />
          </div>
        </div>
      )}
    </div>
  )
}
